---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spree-web
  labels:
    app: spree-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spree-web
  template:
    metadata:
      labels:
        app: spree-web
    spec:
      containers:
      - name: spree
        image: tudfinalproject/spree
        ports:
        - containerPort: 4000